import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // ✅ import Poppins font
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

// ✅ Initialize Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // তুমি চাইলে নির্দিষ্ট font weight গুলো দিতে পারো
  variable: "--font-poppins", // optional variable name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased pt-[190px]`}>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
